[package]
name = "trs80-web"
version = "0.1.0"
description = "Liaison WebAssembly de l'émulateur TRS-80"
edition.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
trs80 = { path = "../trs80" }
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O3"]
